# Generated by Django 4.2.1 on 2023-05-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0003_alter_race_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='call',
        ),
    ]
