# Generated by Django 4.2.1 on 2023-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0004_remove_race_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='endDate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='startDate',
        ),
        migrations.AddField(
            model_name='race',
            name='firstCall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='raceNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='secondCall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='maidens',
            field=models.BooleanField(default=False),
        ),
    ]
