# Generated by Django 4.2.1 on 2023-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0005_rename_enddate_race_date_remove_race_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='fieldSize',
            field=models.IntegerField(default=0),
        ),
    ]
