# Generated by Django 4.2.1 on 2023-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0009_remove_race_unique_race_race_unique_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.CharField(default='5 Furlongs', max_length=50),
        ),
    ]
