# Generated by Django 4.2.1 on 2023-05-24 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='endDate',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
        migrations.AddField(
            model_name='race',
            name='startDate',
            field=models.DateField(default=datetime.date(2015, 1, 1)),
        ),
    ]
