# Generated by Django 4.2.1 on 2023-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0007_race_unique_race'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='race',
            name='unique_race',
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('date', 'track', 'raceNumber'), name='Unique Race'),
        ),
    ]
