# Generated by Django 4.2.1 on 2023-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0008_remove_race_unique_race_race_unique_race'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='race',
            name='Unique Race',
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('date', 'track', 'raceNumber'), name='unique_race'),
        ),
    ]
