# Generated by Django 4.2.1 on 2023-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0010_race_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(max_length=50),
        ),
    ]
