# Generated by Django 4.2.1 on 2023-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0011_alter_race_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='firstCall',
            new_name='firstCallPosition',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='secondCall',
            new_name='secondCallLengthsBehind',
        ),
        migrations.AddField(
            model_name='race',
            name='firstCallLengthsBehind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='secondCallPosition',
            field=models.IntegerField(default=0),
        ),
    ]
