# Generated by Django 4.2.1 on 2023-06-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0012_rename_firstcall_race_firstcallposition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='firstCallPosition',
            new_name='firstCall',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='secondCallPosition',
            new_name='secondCall',
        ),
    ]
