# Generated by Django 4.2.1 on 2023-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRABias', '0013_rename_firstcallposition_race_firstcall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='firstCallLengthsBehind',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='secondCallLengthsBehind',
            field=models.FloatField(default=0),
        ),
    ]
